services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petfoster-api
    # command: pnpm run start
    ports:
      - '3000:3000'
    depends_on:
      petfoster-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Exclusion des node_modules pour éviter les conflits

  petfoster-db:
    image: postgres
    container_name: petfoster-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - petfoster-volume:/var/lib/postgresql/data

volumes:
  petfoster-volume:
