BEGIN;

DROP TABLE IF EXISTS "users", "animals", "animals_has_users", "animals_pictures", "species", "messages", "home_profiles", "users_pictures", "welcome_requests" CASCADE ;

CREATE TABLE IF NOT EXISTS "species" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "name" varchar(255) NOT NULL,
   "detail" varchar(255),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "users" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "type_user" varchar(255) NOT NULL,
   "name" varchar(255) NOT NULL,
   "email" varchar(255) NOT NULL UNIQUE,
   "password" text NOT NULL,
   "country" varchar(255) NOT NULL,
   "zip" integer NOT NULL,
   "city" varchar(255) NOT NULL,
   "longitude" numeric(9,6) NOT NULL,
   "latitude" numeric(9,6) NOT NULL,
   "phone" varchar(20),
   "address" varchar(255),
   "website" varchar(255),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "animals" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "name" varchar(255) NOT NULL,
   "date_of_birth" date,
   "sexe" char(1) NOT NULL,
   "race" varchar(255),
   "short_story" varchar(255),
   "long_story" text,
   "health" varchar(255),
   "species_id" INTEGER NOT NULL REFERENCES "species"("id"),
   "creator_id" INTEGER NOT NULL REFERENCES "users"("id"),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz


);

CREATE TABLE IF NOT EXISTS "animals_has_users" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "animals_id" INTEGER NOT NULL REFERENCES "animals"("id"),
   "users_id" INTEGER NOT NULL REFERENCES "users"("id"),
   "date_start" date,
   "date_end" date,
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz


);

CREATE TABLE IF NOT EXISTS "animals_pictures" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "URL_picture" varchar(255) NOT NULL,
   "animals_id" integer NOT NULL REFERENCES "animals"("id"),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "messages" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "sender_id" integer NOT NULL REFERENCES "users"("id"),
   "receiver_id" integer NOT NULL REFERENCES "users"("id"),
   "content" text NOT NULL,
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "fosterling_profiles" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "age" varchar,
   "sexe" char(1),
   "search_area" integer,
   "users_id" integer NOT NULL REFERENCES "users"("id"),
   "species_id" integer NOT NULL REFERENCES "species"("id"),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "users_pictures" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "URL_picture" varchar(255) NOT NULL,
   "users_id" integer NOT NULL REFERENCES "users"("id"),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

CREATE TABLE IF NOT EXISTS "fosterling_requests" (
   "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   "request_status" varchar(255) NOT NULL,
   "content_request" text,
   "animals_id" integer NOT NULL REFERENCES "animals"("id"),
   "users_id" integer NOT NULL REFERENCES "users"("id"),
   "created_at" timestamptz NOT NULL DEFAULT NOW(),
   "updated_at" timestamptz
  
);

COMMIT;